name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  podspec:
    runs-on: macOS-11
    steps:
    - uses: actions/checkout@v2
    - run: bundle install
    - run: bundle exec pod lib lint
    - run: ls -la
  build_mac:
    runs-on: macOS-11
    steps:
    - uses: actions/checkout@v2
    - run: gem install fastlane
    - run: fastlane gym --configuration Debug --skip_archive --scheme 'WatchFaceDumper'
    - run: find /Users/runner/Library/Developer/Xcode/DerivedData -name WatchFaceDumper.app
